name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install yarn jest
          yarn
      - name: Zip Node_Modules
        run: tar -czf node_modules.tar.gz ./node_modules
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./node_modules.tar.gz

  # test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run tests
  #       run: |
  #         yarn
  #         yarn test
  # lint:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Lint
  #       run: |
  #         yarn
  #         yarn lint
  # prettier:
    # runs-on: ubuntu-latest
    # needs: build
    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Prettier
    #     run: |
    #       yarn
    #       yarn prettier